openapi: 3.0.3
info:
  title: Graphipedia API
  description: >
    Graphipedia is an API that searches links between Wikipedia articles and finds the shortest path from a start article to a goal article.
    This API provides two main functions: title search and graph search.
  version: 1.0.0
  contact:
    name: YarmUI

servers:
  - url: http://localhost:3000
    description: Local Development Environment
  - url: https://graphipedia.dog-right.dev
    description: Production Environment (Example)

paths:
  /api/search:
    get:
      summary: Title Search
      description: Searches article titles with partial matching and returns a list of matching Wikipedia articles
      operationId: titleSearch
      parameters:
        - name: query
          in: query
          description: Search query string
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TitleSearchResult'

  /api/graph_search:
    get:
      summary: Graph Search
      description: |
        Searches for the shortest path from a start article to an end article.
        Uses a bidirectional breadth-first search algorithm for efficient searching.
      operationId: graphSearch
      parameters:
        - name: start
          in: query
          description: Title of the start article
          required: true
          schema:
            type: string
        - name: end
          in: query
          description: Title of the end article
          required: true
          schema:
            type: string
        - name: enable_date_related
          in: query
          description: Whether to include date-related articles in the search
          required: false
          schema:
            type: boolean
            default: false
        - name: enable_list_article
          in: query
          description: Whether to include list articles in the search
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphSearchResult'

components:
  schemas:
    TitleSearchQuery:
      type: object
      properties:
        query:
          type: string
          description: Search query string
        limit:
          type: integer
          description: Maximum number of results to return
          nullable: true
      required:
        - query

    TitleSearchResult:
      type: object
      properties:
        query:
          $ref: '#/components/schemas/TitleSearchQuery'
        items:
          type: array
          items:
            $ref: '#/components/schemas/TitleSearchResultItem'
        duration:
          $ref: '#/components/schemas/Duration'
      required:
        - query
        - items
        - duration

    TitleSearchResultItem:
      type: object
      properties:
        title:
          type: string
          description: Article title
        id:
          type: integer
          format: int32
          description: Article ID
        is_redirect:
          type: boolean
          description: Whether the article is a redirect
        redirected_title:
          type: string
          description: Title of the article being redirected to
          nullable: true
        redirected_id:
          type: integer
          format: int32
          description: ID of the article being redirected to
          nullable: true
        link_count:
          type: integer
          description: Total number of links (forward + backward)
        forward_link_count:
          type: integer
          description: Number of forward links
        backward_link_count:
          type: integer
          description: Number of backward links
      required:
        - title
        - id
        - is_redirect
        - link_count
        - forward_link_count
        - backward_link_count

    GraphSearchQuery:
      type: object
      properties:
        start:
          type: string
          description: Title of the start article
        end:
          type: string
          description: Title of the end article
        enable_date_related:
          type: boolean
          description: Whether to include date-related articles in the search
          nullable: true
        enable_list_article:
          type: boolean
          description: Whether to include list articles in the search
          nullable: true
      required:
        - start
        - end

    GraphSearchResult:
      type: object
      properties:
        discovered_nodes:
          type: integer
          format: int32
          description: Number of nodes discovered during the search
        visited_nodes:
          type: integer
          format: int32
          description: Number of nodes visited during the search
        start_node:
          $ref: '#/components/schemas/GraphSearchResultNode'
          description: Information about the start node
          nullable: true
        end_node:
          $ref: '#/components/schemas/GraphSearchResultNode'
          description: Information about the end node
          nullable: true
        start_node_search_result:
          $ref: '#/components/schemas/TitleSearchResultItem'
          description: Detailed search information about the start node
          nullable: true
        end_node_search_result:
          $ref: '#/components/schemas/TitleSearchResultItem'
          description: Detailed search information about the end node
          nullable: true
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/GraphSearchResultNode'
          description: List of nodes in the path
        edges:
          type: array
          items:
            type: array
            items:
              type: integer
              format: int32
            minItems: 2
            maxItems: 2
          description: List of edges (links) in the path. Each element is in the format [from_node_id, to_node_id]
        start_not_found:
          type: boolean
          description: Whether the start node was not found
        end_not_found:
          type: boolean
          description: Whether the end node was not found
        route_found:
          type: boolean
          description: Whether a route was found
        is_start_end_some:
          type: boolean
          description: Whether both the start and end nodes were found
        duration:
          $ref: '#/components/schemas/Duration'
          description: Time taken for the search
      required:
        - discovered_nodes
        - visited_nodes
        - nodes
        - edges
        - start_not_found
        - end_not_found
        - route_found
        - is_start_end_some
        - duration

    GraphSearchResultNode:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Node ID
        ns:
          type: integer
          format: int32
          description: Namespace ID
        title:
          type: string
          description: Article title
        is_redirect:
          type: boolean
          description: Whether the article is a redirect
        is_date_related:
          type: boolean
          description: Whether the article is date-related
        is_list_article:
          type: boolean
          description: Whether the article is a list article
        distance:
          type: integer
          format: int8
          description: Distance from the start node
      required:
        - id
        - ns
        - title
        - is_redirect
        - is_date_related
        - is_list_article
        - distance

    Duration:
      type: object
      properties:
        secs:
          type: integer
          format: int64
          description: Seconds
        nanos:
          type: integer
          format: int32
          description: Nanoseconds
      required:
        - secs
        - nanos